---
title: "analyze"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r}
rm(list = ls())
library(data.table); library(tidyverse); library(correlation)
library(BayesFactor); library(BFpack); library(ggbeeswarm); library(patchwork); library(ggdist)
library(hausekeep)
library(marginaleffects)
theme_set(theme_minimal())
```

```{r}
d0_feed <- fread("../data/clean/data_feed.csv")

d0_feed <- d0_feed[attention == 1.0 & ipblock == 0]
d0_feed[, .(mean_n_dwells = mean(n_dwells, na.rm = T), mean_dwell = mean(dwell, na.rm = T), mean_ldwell = mean(ldwell, na.rm = T)), by = .(user_id, entity_set, condition)][, .(mean2_n_dwells = mean(mean_n_dwells, na.rm = T), mean2_dwell = mean(mean_dwell, na.rm = T), mean2_ldwell = mean(mean_ldwell, na.rm = T)), keyby = .(condition, entity_set)]
d0_feed[, .(mean_n_dwells = mean(n_dwells, na.rm = T), mean_dwell = mean(dwell, na.rm = T), mean_ldwell = mean(ldwell, na.rm = T)), by = .(user_id, condition)][, .(mean2_n_dwells = mean(mean_n_dwells, na.rm = T), mean2_dwell = mean(mean_dwell, na.rm = T), mean2_ldwell = mean(mean_ldwell, na.rm = T)), keyby = .(condition)]
library(fixest)
feols(ldwell ~ condition, d0_feed[entity_set == 'oct9_news' & dwell>2000], cluster = ~user_id+entity_id)

feols(dwell ~ condition, d0_feed, cluster = ~user_id)
feols(n_dwells ~ condition, d0_feed, cluster = ~user_id)
feglm(n_dwells ~ condition, d0_feed, cluster = ~user_id, family = 'quasipoisson')

hist(d0_feed$ldwell)
hist(d0_feed$dwell)
hist(d0_feed$n_dwells)

d1 <- fread("../data/clean/data.csv")
d1[, n_distinct(user_id), keyby = .(condition)]
d1[, n_distinct(user_id), keyby = .(condition, attention, ipblock)]  
# users per condition

d2 <- d1[attention == 1.0 & ipblock == 0]
d2[, n_distinct(user_id), keyby = .(condition, attention, ipblock)]
d2[, n_distinct(user_id)]
d2[, n_distinct(user_id), condition]

# remove alphanumeric response column, ip address and country codes
d2 <- select(d2, user_id, condition, field, news_eval)
perc <- d2[field == "climate_cards_perc", .(user_id, news_eval)]
setnames(perc, c("user_id", "climate_perc"))
perc

d2 <- d2[field != "climate_cards_perc"] |> left_join(perc) 
setDT(d2)
```

```{r}
d2[, unique(field)]
d2[grepl("climate_", field), topic := "climate"]
d2[grepl("johnny_", field), topic := "johnny"]
d2[grepl("election_", field), topic := "election"]
d2[, .(field, topic)][order(field)] |> distinct()

d2[, question := field]
d2[, question := gsub("climate_", "", question)]
d2[, question := gsub("johnny_", "", question)]
d2[, question := gsub("election_", "", question)]
d2[, .(field, question)][order(question)] |> distinct()

d2[, .(field, topic, question)][order(topic, question)] |> distinct()

d3 <- dcast(d2, user_id + condition + topic + climate_perc ~ question, value.var = "news_eval")
d3[, rating_combined := (importance + newsworthiness) / 2]
d3
```

```{r check correlations}
cors <- d3[, .(r = cor(importance, newsworthiness)), topic]
cors
ggplot(d3, aes(importance, newsworthiness)) +
    facet_wrap(~ topic) +
    geom_jitter() +
    geom_smooth(method = 'lm', alpha = 0.1) 

select(d3, topic, importance, newsworthiness) %>% group_by(topic) %>% correlation()


correlation(d3[topic == "climate"])
```


```{r}
d4 <- distinct(d3[, .(user_id, condition, climate_perc)])
d4[, condition := condition + 0.5]
summaryh(lm(climate_perc ~ condition, d4))

p1 <- ggplot(d4, aes(factor(condition, labels = c("control", "treatment")), climate_perc)) +
    geom_quasirandom(alpha = 0.5, size = 0.8) +
    stat_summary(fun = mean, geom = 'point', shape = 95, size = 6) +
    stat_summary(fun.data = mean_cl_normal, geom = 'errorbar', width = 0, size = 1.1) +
    scale_y_continuous(limits = c(0, 100)) +
    labs(x = "", y = "self-reported percent climate cards seen")
p1

ggsave("../figures/manipulation_check.png", p1, dpi = 300, width = 5, height = 5, bg = "white")
```


```{r fit models}
# if cor is < 0.7 interpret this
ttestBF(formula = importance ~ condition, data = d3[topic == "climate"])
m1_imp <- lm(importance ~ condition, d3[topic == "climate"])
summaryh(m1_imp)
m1_impbf <- BF(m1_imp, hypothesis = "condition = 0")
summary(m1_impbf)

ttestBF(formula = newsworthiness ~ condition, data = d3[topic == "climate"])
m1_newsw <- lm(newsworthiness ~ condition, d3[topic == "climate"])
summaryh(m1_newsw)
m1_newswbf <- BF(m1_newsw, hypothesis = "condition = 0")
summary(m1_newswbf)

# if cor > 0.7, interpret this
ttestBF(formula = rating_combined ~ condition, data = d3[topic == "climate"])
m1_combine <- lm(rating_combined ~ condition, d3[topic == "climate"])
summaryh(m1_combine)
m1_combinebf <- BF(m1_combine, hypothesis = "condition = 0")
summary(m1_combinebf)
```


```{r}

#compute bayes factor of 20 ppl
#then loop to add 1 person at a time, to compute bayes factor at each itertn
# do till last subject, get N-20 bayes factors, save p values
# might hit 0.1 or 10 at some pt in middle
# plot bayes factors as function of iteration
# correlate p vals and bayes factors - sign or not?, no corr if there is no effect

#n, bf1, pval1, bf2, pval2 - do for importance
library(stringr)
BFs <- {}
Ns <- {}
Ps <- {}

for (i in 20:nrow(d3[topic == "climate"])) {
  testOutput <- ttestBF(formula = importance ~ condition, data = d3[topic == "climate"][1:i,])
  m1_imp <- lm(importance ~ condition, d3[topic == "climate"][1:i,])
  m1_imp_testOutput <- summaryh(m1_imp)
  res <- str_match(m1_imp_testOutput[term == "condition"]$results, "p = \\s*(.*?)\\s*,")
  BFs <- append(BFs, testOutput@bayesFactor[["bf"]])
  Ns <- append(Ns, i)
  Ps <- append(Ps, res[,2])
}

png("../figures/BF_history_imp.png")
plot(Ns, exp(BFs))
dev.off()

png("../figures/P_history_imp.png")
plot(Ns, Ps)
dev.off()

png("../figures/P_BF_corr_imp.png")
plot(exp(BFs), Ps)
text(paste("Correlation:", cor(exp(BFs), as.numeric(Ps), method = "pearson")), x = 0.5, y = 0.5)
dev.off()



BFs <- {}
Ns <- {}
Ps <- {}

for (i in 20:nrow(d3[topic == "climate"])) {
  testOutput <- ttestBF(formula = newsworthiness ~ condition, data = d3[topic == "climate"][1:i,])
  m1_newsw <- lm(newsworthiness ~ condition, d3[topic == "climate"][1:i,])
  m1_newsw_testOutput <- summaryh(m1_newsw)
  res <- str_match(m1_newsw_testOutput[term == "condition"]$results, "p = \\s*(.*?)\\s*,")
  BFs <- append(BFs, testOutput@bayesFactor[["bf"]])
  Ns <- append(Ns, i)
  Ps <- append(Ps, res[,2])
}

png("../figures/BF_history_newsw.png")
plot(Ns, exp(BFs))
dev.off()

png("../figures/P_history_newsw.png")
plot(Ns, Ps)
dev.off()

png("../figures/P_BF_corr_newsw.png")
plot(exp(BFs), Ps)
text(paste("Correlation:", cor(exp(BFs), as.numeric(Ps), method = "pearson")), x = 0.5, y = 0.5)
dev.off()


```


```{r}
dodge <- 0.5
p2 <- ggplot(d2, aes(question, news_eval, col = factor(condition, labels = c("control", "treatment")))) +
    facet_grid(topic ~ .) +
    geom_quasirandom(alpha = 0.1, dodge = dodge, size = 0.8) +
    stat_summary(fun = mean, geom = 'point', shape = 95, size = 6, position = position_dodge(dodge)) +
    stat_summary(fun.data = mean_cl_normal, geom = 'errorbar', width = 0, size = 1.1, position = position_dodge(dodge)) +
    scale_y_continuous(limits = c(-2, 8), breaks = 1:6) +
    labs(x = "", y = "rating", col = "condition")
p2

ggsave("../figures/main_effect.png", p2, dpi = 300, width = 13, height = 8, bg = "white")
```

```{r interact perc with condition}
d3[, climate_percC := climate_perc - mean(climate_perc, na.rm = T)]
m1 <- lm(importance ~ condition * climate_percC, d3[topic == "climate"])
summaryh(m1)

m2 <- lm(newsworthiness ~ condition * climate_percC, d3[topic == "climate"])
summaryh(m2)

m3 <- lm(rating_combined ~ condition * climate_percC, d3[topic == "climate"])
summaryh(m3)

d3[climate_perc %in% c(5, 35), .(climate_perc, climate_percC)] |> distinct()
marginaleffects(m3, datagrid(climate_percC = c(-30.54032, -0.5403226), condition = c(-0.5, 0.5)))

m1 <- lm(importance ~ climate_percC, d3[topic == "climate"])
summaryh(m1)
m2 <- lm(newsworthiness ~ climate_percC, d3[topic == "climate"])
summaryh(m2)
m3 <- lm(rating_combined ~ climate_percC, d3[topic == "climate"])
summaryh(m3)
```



```{r fit models to people who reported seeing "correct" no. of climate headlines}
d3a <- d3[(condition == -0.5 & climate_perc < 20) | (condition == 0.5 & climate_perc > 33)]
d3a[, fivenum(climate_perc), condition]
d3a[, n_distinct(user_id), condition]
user_subset <- d3a[, unique(user_id)]

# if cor is < 0.7 interpret this
ttestBF(formula = importance ~ condition, data = d3a[topic == "climate"])
m1_imp <- lm(importance ~ condition, d3a[topic == "climate"])
summaryh(m1_imp)
m1_impbf <- BF(m1_imp, hypothesis = "condition = 0")
summary(m1_impbf)

ttestBF(formula = newsworthiness ~ condition, data = d3a[topic == "climate"])
m1_newsw <- lm(newsworthiness ~ condition, d3a[topic == "climate"])
summaryh(m1_newsw)
m1_newswbf <- BF(m1_newsw, hypothesis = "condition = 0")
summary(m1_newswbf)

# if cor > 0.7, interpret this
ttestBF(formula = rating_combined ~ condition, data = d3a[topic == "climate"])
m1_combine <- lm(rating_combined ~ condition, d3a[topic == "climate"])
summaryh(m1_combine)
m1_combinebf <- BF(m1_combine, hypothesis = "condition = 0")
summary(m1_combinebf)

m1 <- lm(importance ~ condition * climate_percC, d3a[topic == "climate"])
summaryh(m1)
m2 <- lm(newsworthiness ~ condition * climate_percC, d3a[topic == "climate"])
summaryh(m2)
m3 <- lm(rating_combined ~ condition * climate_percC, d3a[topic == "climate"])
summaryh(m3)

m1 <- lm(importance ~ climate_percC, d3a[topic == "climate"])
summaryh(m1)
m2 <- lm(newsworthiness ~ climate_percC, d3a[topic == "climate"])
summaryh(m2)
m3 <- lm(rating_combined ~ climate_percC, d3a[topic == "climate"])
summaryh(m3)
```

```{r}
d4a <- distinct(d3a[, .(user_id, condition, climate_perc)])

p1 <- ggplot(d4a, aes(factor(condition, labels = c("control", "treatment")), climate_perc)) +
    geom_quasirandom(alpha = 0.5, size = 0.8) +
    stat_summary(fun = mean, geom = 'point', shape = 95, size = 6) +
    stat_summary(fun.data = mean_cl_normal, geom = 'errorbar', width = 0, size = 1.1) +
    scale_y_continuous(limits = c(0, 100)) +
    labs(x = "", y = "self-reported percent climate cards seen")
p1

ggsave("../figures/manipulation_check_subset.png", p1, dpi = 300, width = 5, height = 5, bg = "white")
```

```{r}
dodge <- 0.5
p2a <- ggplot(d2[user_id %in% user_subset], aes(question, news_eval, col = factor(condition, labels = c("control", "treatment")))) +
    facet_grid(topic ~ .) +
    geom_quasirandom(alpha = 0.1, dodge = dodge, size = 0.8) +
    stat_summary(fun = mean, geom = 'point', shape = 95, size = 6, position = position_dodge(dodge)) +
    stat_summary(fun.data = mean_cl_normal, geom = 'errorbar', width = 0, size = 1.1, position = position_dodge(dodge)) +
    scale_y_continuous(limits = c(-2, 8), breaks = 1:6) +
    labs(x = "", y = "rating", col = "condition")
p2a

ggsave("../figures/main_effect_subset.png", p2a, dpi = 300, width = 13, height = 8, bg = "white")
```

```{r other effects}
# climate
ttestBF(formula = exposure_frequency ~ condition, data = d3[topic == "climate"])
summaryh(lm(exposure_frequency ~ condition, d3[topic == "climate"]))

ttestBF(formula = exposure_frequency ~ condition, data = d3a[topic == "climate"])
summaryh(lm(exposure_frequency ~ condition, d3a[topic == "climate"]))

ttestBF(formula = desired_frequency ~ condition, data = d3[topic == "climate"])
summaryh(lm(desired_frequency ~ condition, d3[topic == "climate"]))

ttestBF(formula = hope ~ condition, data = d3[topic == "climate"])
summaryh(lm(hope ~ condition, d3[topic == "climate"]))

ttestBF(formula = concern ~ condition, data = d3[topic == "climate"])
summaryh(lm(concern ~ condition, d3[topic == "climate"]))


# election
ttestBF(formula = importance ~ condition, data = d3[topic == "election"])
summaryh(lm(importance ~ condition, d3[topic == "election"]))

ttestBF(formula = newsworthiness ~ condition, data = d3[topic == "election"])
summaryh(lm(newsworthiness ~ condition, d3[topic == "election"]))

ttestBF(formula = rating_combined ~ condition, data = d3[topic == "election"])
summaryh(lm(rating_combined ~ condition, d3[topic == "election"]))

ttestBF(formula = desired_frequency ~ condition, data = d3[topic == "election"])
summaryh(lm(desired_frequency ~ condition, d3[topic == "election"]))

ttestBF(formula = exposure_frequency ~ condition, data = d3[topic == "election"])
summaryh(lm(exposure_frequency ~ condition, d3[topic == "election"]))


# johnny
ttestBF(formula = exposure_frequency ~ condition, data = d3[topic == "johnny"])
summaryh(lm(exposure_frequency ~ condition, d3[topic == "johnny"]))

ttestBF(formula = exposure_frequency ~ condition, data = d3a[topic == "johnny"])
summaryh(lm(exposure_frequency ~ condition, d3a[topic == "johnny"]))

ttestBF(formula = newsworthiness ~ condition, data = d3[topic == "johnny"])
summaryh(lm(newsworthiness ~ condition, d3[topic == "johnny"]))

ttestBF(formula = rating_combined ~ condition, data = d3[topic == "johnny"])
summaryh(lm(rating_combined ~ condition, d3[topic == "johnny"]))

ttestBF(formula = desired_frequency ~ condition, data = d3[topic == "johnny"])
summaryh(lm(desired_frequency ~ condition, d3[topic == "johnny"]))

ttestBF(formula = exposure_frequency ~ condition, data = d3[topic == "johnny"])
summaryh(lm(exposure_frequency ~ condition, d3[topic == "johnny"]))
```









```{r}
# https://mjskay.github.io/ggdist/articles/dotsinterval.html
set.seed(12345) # for reproducibility
d3[, condition := factor(condition, labels = c("control", "treatment"))]
p3 <- ggplot(d3, aes(y = topic, x = importance, fill = topic)) +
    facet_grid(condition ~ topic) +
    stat_slab(aes(thickness = stat(pdf*n)), scale = 0.7) +
    stat_dotsinterval(side = "bottom", scale = 0.3, slab_size = NA)
p3
ggsave("../figures/rain_cloud_plot_importance.png", p3, dpi = 300, width = 8, height = 8, bg = "white")

p3 <- ggplot(d3, aes(y = topic, x = newsworthiness, fill = topic)) +
    facet_grid(condition ~ topic) +
    stat_slab(aes(thickness = stat(pdf*n)), scale = 0.7) +
    stat_dotsinterval(side = "bottom", scale = 0.3, slab_size = NA)
p3

ggsave("../figures/rain_cloud_plot_newsworthiness.png", p3, dpi = 300, width = 8, height = 8, bg = "white")

p3 <- ggplot(d3, aes(y = topic, x = rating_combined, fill = topic)) +
    facet_grid(condition ~ topic) +
    stat_slab(aes(thickness = stat(pdf*n)), scale = 0.7) +
    stat_dotsinterval(side = "bottom", scale = 0.3, slab_size = NA)
p3

ggsave("../figures/rain_cloud_plot_combined.png", p3, dpi = 300, width = 8, height = 8, bg = "white")
```



```{r}
# interact condition with ideology
d_ideology <- fread("../data/clean/data-wide.csv")
d_ideology <- select(d_ideology, -starts_with("aot_"))
d_demo <- left_join(d3[topic == "climate"], d_ideology) |> data.table()

d_demo <- mutate_if(d_demo, is.integer, as.numeric) |> data.table()
d_demo[, table(condition)]

d_demo[, hist(politicalpref)]
d_demo[, hist(economicissuespref)]
d_demo[, hist(socialissuespref)]
d_demo[, hist(aot)]

glimpse(d_demo)

cols <- select(d_demo, economicissuespref:aot, -politicalposition) |> names()
newcols <- paste0(cols, "C")
d_demo[, (newcols) := lapply(.SD, function(x) x - mean(x)), .SDcols = cols]
summary(d_demo)

summaryh(lm(importance ~ condition * politicalprefC, d_demo))
summaryh(lm(newsworthiness ~ condition * politicalprefC, d_demo))
summaryh(lm(hope ~ condition * politicalprefC, d_demo))
summaryh(lm(human_activity ~ condition * politicalprefC, d_demo))
summaryh(lm(problem ~ condition * politicalprefC, d_demo))
summaryh(lm(concern ~ condition * politicalprefC, d_demo))
summaryh(lm(exposure_frequency ~ condition * politicalprefC, d_demo))
summaryh(lm(desired_frequency ~ condition * politicalprefC, d_demo))

summaryh(lm(importance ~ condition * economicissuesprefC, d_demo))
summaryh(lm(newsworthiness ~ condition * economicissuesprefC, d_demo))
summaryh(lm(hope ~ condition * economicissuesprefC, d_demo))
summaryh(lm(human_activity ~ condition * economicissuesprefC, d_demo))
summaryh(lm(problem ~ condition * economicissuesprefC, d_demo))
summaryh(lm(concern ~ condition * economicissuesprefC, d_demo))
summaryh(lm(exposure_frequency ~ condition * economicissuesprefC, d_demo))
summaryh(lm(desired_frequency ~ condition * economicissuesprefC, d_demo))

summaryh(lm(importance ~ condition * socialissuesprefC, d_demo))
summaryh(lm(newsworthiness ~ condition * socialissuesprefC, d_demo))
summaryh(lm(hope ~ condition * socialissuesprefC, d_demo))
summaryh(lm(human_activity ~ condition * socialissuesprefC, d_demo))
summaryh(lm(problem ~ condition * socialissuesprefC, d_demo))
summaryh(lm(concern ~ condition * socialissuesprefC, d_demo))
summaryh(lm(exposure_frequency ~ condition * socialissuesprefC, d_demo))
summaryh(lm(desired_frequency ~ condition * socialissuesprefC, d_demo))

summaryh(lm(importance ~ condition * aotC, d_demo))
summaryh(lm(newsworthiness ~ condition * aotC, d_demo))
summaryh(lm(hope ~ condition * aotC, d_demo))
summaryh(lm(human_activity ~ condition * aotC, d_demo))
summaryh(lm(problem ~ condition * aotC, d_demo))
summaryh(lm(concern ~ condition * aotC, d_demo))
summaryh(lm(exposure_frequency ~ condition * aotC, d_demo))
summaryh(lm(desired_frequency ~ condition * aotC, d_demo))


summaryh(lm(importance ~ condition * politicalprefC, d_demo[user_id %in% user_subset]))
summaryh(lm(newsworthiness ~ condition * politicalprefC, d_demo[user_id %in% user_subset]))
summaryh(lm(hope ~ condition * politicalprefC, d_demo[user_id %in% user_subset]))
summaryh(lm(human_activity ~ condition * politicalprefC, d_demo[user_id %in% user_subset]))
summaryh(lm(problem ~ condition * politicalprefC, d_demo[user_id %in% user_subset]))
summaryh(lm(concern ~ condition * politicalprefC, d_demo[user_id %in% user_subset]))
summaryh(lm(exposure_frequency ~ condition * politicalprefC, d_demo[user_id %in% user_subset]))
summaryh(lm(desired_frequency ~ condition * politicalprefC, d_demo[user_id %in% user_subset]))

summaryh(lm(importance ~ condition * economicissuesprefC, d_demo[user_id %in% user_subset]))
summaryh(lm(newsworthiness ~ condition * economicissuesprefC, d_demo[user_id %in% user_subset]))
summaryh(lm(hope ~ condition * economicissuesprefC, d_demo[user_id %in% user_subset]))
summaryh(lm(human_activity ~ condition * economicissuesprefC, d_demo[user_id %in% user_subset]))
summaryh(lm(problem ~ condition * economicissuesprefC, d_demo[user_id %in% user_subset]))
summaryh(lm(concern ~ condition * economicissuesprefC, d_demo[user_id %in% user_subset]))
summaryh(lm(exposure_frequency ~ condition * economicissuesprefC, d_demo[user_id %in% user_subset]))
summaryh(lm(desired_frequency ~ condition * economicissuesprefC, d_demo[user_id %in% user_subset]))

summaryh(lm(importance ~ condition * socialissuesprefC, d_demo[user_id %in% user_subset]))
summaryh(lm(newsworthiness ~ condition * socialissuesprefC, d_demo[user_id %in% user_subset]))
summaryh(lm(hope ~ condition * socialissuesprefC, d_demo[user_id %in% user_subset]))
summaryh(lm(human_activity ~ condition * socialissuesprefC, d_demo[user_id %in% user_subset]))
summaryh(lm(problem ~ condition * socialissuesprefC, d_demo[user_id %in% user_subset]))
summaryh(lm(concern ~ condition * socialissuesprefC, d_demo[user_id %in% user_subset]))
summaryh(lm(exposure_frequency ~ condition * socialissuesprefC, d_demo[user_id %in% user_subset]))
summaryh(lm(desired_frequency ~ condition * socialissuesprefC, d_demo[user_id %in% user_subset]))

summaryh(lm(importance ~ condition * aotC, d_demo[user_id %in% user_subset]))
summaryh(lm(newsworthiness ~ condition * aotC, d_demo[user_id %in% user_subset]))
summaryh(lm(hope ~ condition * aotC, d_demo[user_id %in% user_subset]))
summaryh(lm(human_activity ~ condition * aotC, d_demo[user_id %in% user_subset]))
summaryh(lm(problem ~ condition * aotC, d_demo[user_id %in% user_subset]))
summaryh(lm(concern ~ condition * aotC, d_demo[user_id %in% user_subset]))
summaryh(lm(exposure_frequency ~ condition * aotC, d_demo[user_id %in% user_subset]))
summaryh(lm(desired_frequency ~ condition * aotC, d_demo[user_id %in% user_subset]))
```











```{r}
d3[, condition := factor(condition, labels = c(-0.5, 0.5))]
d3$condition <- as.numeric(as.character(d3$condition))
d0_feed <- fread("../data/clean/data_feed.csv")
d0_feed <- mutate_if(d0_feed, is.integer, as.numeric) |> data.table()
glimpse(d0_feed)

d0_feed[, engage := likes_1 + shares_1 + read_later_1]
d0_feed[, engaged := 0]
d0_feed[likes_1 > 0 | shares_1 > 0 | read_later_1 > 0, engaged := 1]

# did people engage with first headline? yes
d0_feed[item_order == 0, .N, keyby = .(condition, engage, entity_id)]

# export/save as covariate
temp <- d0_feed[item_order == 0, .(user_id, engage_firstheadline = engage, condition)]
# fwrite(temp, "../data/clean/first_headline_engagement.csv")

temp2 <- left_join(d3[topic == "climate"], temp)
setDT(temp2)
glimpse(temp2)
temp3 <- copy(temp2)
temp2[, hist(engage_firstheadline)]
temp2[, engage_firstheadline := log(engage_firstheadline + 1)]
temp2[, engage_firstheadline := engage_firstheadline - mean(engage_firstheadline)]
temp2[, mean(engage_firstheadline)]
temp2[, hist(engage_firstheadline, breaks = 10)]


m1_imp <- lm(importance ~ condition, d3[topic == "climate"])
summaryh(m1_imp)
m1_imp <- lm(importance ~ condition + engage_firstheadline, temp2)
summaryh(m1_imp)

# TODO: compute bayes factor (via model comparison)
# https://richarddmorey.github.io/BayesFactor/#regression

m1_imp <- lm(newsworthiness ~ condition, d3[topic == "climate"])
summaryh(m1_imp)
m1_imp <- lm(newsworthiness ~ condition + engage_firstheadline, temp2)
summaryh(m1_imp)

# TODO: compute bayes factor 
```























# other


```{r}
glimpse(d0_feed)

d0_feed <- d0_feed[attention == 1 & ipblock == 0]

d0_feed[, engage := likes_1 + shares_1 + read_later_1]
d0_feed[, engaged := 0]
d0_feed[likes_1 > 0 | shares_1 > 0 | read_later_1 > 0, engaged := 1]


d0_feed_cc <- d0_feed[entity_set == "22051858_climate"]

p1 <- ggplot(d0_feed_cc, aes(item_order, dwell)) +
    geom_smooth(method = 'lm') +
    stat_summary(fun = mean, geom = 'point', shape = 95, size = 6, position = position_dodge(1)) +
    stat_summary(fun.data = mean_cl_normal, geom = 'errorbar', width = 0, size = 0.8, position = position_dodge(1))

p2 <- ggplot(d0_feed_cc, aes(item_order, likes_1)) +
    geom_smooth(method = 'lm') +
    stat_summary(fun = mean, geom = 'point', shape = 95, size = 6, position = position_dodge(1)) +
    stat_summary(fun.data = mean_cl_normal, geom = 'errorbar', width = 0, size = 0.8, position = position_dodge(1))

p3 <- ggplot(d0_feed_cc, aes(item_order, shares_1)) +
    geom_smooth(method = 'lm') +
    stat_summary(fun = mean, geom = 'point', shape = 95, size = 6, position = position_dodge(1)) +
    stat_summary(fun.data = mean_cl_normal, geom = 'errorbar', width = 0, size = 0.8, position = position_dodge(1))

p4 <- ggplot(d0_feed_cc, aes(item_order, read_later_1)) +
    geom_smooth(method = 'lm') +
    stat_summary(fun = mean, geom = 'point', shape = 95, size = 6, position = position_dodge(1)) +
    stat_summary(fun.data = mean_cl_normal, geom = 'errorbar', width = 0, size = 0.8, position = position_dodge(1))

p1 / p2 / p3 / p4



include <- d0_feed_cc[condition == 0.5 & engaged == 0, .N, user_id][N > 5, user_id]
coefs <- d0_feed_cc[condition == 0.5 & user_id %in% include, .(b1 = coef(lm(ldwell ~ item_order))[2]), user_id]
coefs

feed_avg <- d0_feed_cc[condition == 0.5, .(like = mean(likes_1, na.rm = T),
            share = mean(shares_1, na.rm = T),
            read = mean(read_later_1, na.rm = T),
            ldwell = mean(ldwell, na.rm = T),
            n_dwell = mean(n_dwells, na.rm = T),
            engage = mean(engage, na.rm = T)),
           user_id]
feed_avg[order(-engage)]

# exclude extreme engagers
feed_avg <- feed_avg[share < 1.0][like < 1][read < 1]

dwell_engage0 <- d0_feed_cc[engaged == 0, .(ldwell_engage0 = mean(ldwell, na.rm = T)), user_id]

d5 <- left_join(d3, feed_avg) |> left_join(coefs) |> left_join(dwell_engage0) |>  data.table()
d5


d5[topic == "climate" & condition == 0.5, hist(log(like + 1))]
d5[topic == "climate" & condition == 0.5, hist(like)]
summaryh(lm(newsworthiness ~ log(like + 1), d5[topic == "climate" & condition == 0.5]))  # ya
summaryh(lm(newsworthiness ~ like, d5[topic == "climate" & condition == 0.5]))  # ya
summaryh(lm(newsworthiness ~ log(read + 1), d5[topic == "climate" & condition == 0.5]))
summaryh(lm(newsworthiness ~ share, d5[topic == "climate" & condition == 0.5])) # yes
summaryh(lm(newsworthiness ~ log(share + 1), d5[topic == "climate" & condition == 0.5]))
summaryh(lm(newsworthiness ~ ldwell, d5[topic == "climate" & condition == 0.5]))
summaryh(lm(newsworthiness ~ ldwell_engage0, d5[topic == "climate" & condition == 0.5]))
summaryh(lm(newsworthiness ~ n_dwell, d5[topic == "climate" & condition == 0.5]))
summaryh(lm(newsworthiness ~ engage, d5[topic == "climate" & condition == 0.5]))
summaryh(lm(newsworthiness ~ b1, d5[topic == "climate" & condition == 0.5]))
summaryh(lm(newsworthiness ~ like + read + share + ldwell + n_dwell, d5[topic == "climate" & condition == 0.5]))
summaryh(lm(newsworthiness ~ like + read + ldwell, d5[topic == "climate" & condition == 0.5]))
summaryh(lm(newsworthiness ~ like + read + ldwell + climate_perc, d5[topic == "climate" & condition == 0.5]))

summaryh(lm(importance ~ like, d5[topic == "climate" & condition == 0.5]))  #
summaryh(lm(importance ~ log(like + 1), d5[topic == "climate" & condition == 0.5]))  #
summaryh(lm(importance ~ read, d5[topic == "climate" & condition == 0.5]))
summaryh(lm(importance ~ log(read + 1), d5[topic == "climate" & condition == 0.5]))  #
summaryh(lm(importance ~ share, d5[topic == "climate" & condition == 0.5])) # 
summaryh(lm(importance ~ log(share + 1), d5[topic == "climate" & condition == 0.5]))  #
summaryh(lm(importance ~ ldwell, d5[topic == "climate" & condition == 0.5]))
summaryh(lm(importance ~ ldwell_engage0, d5[topic == "climate" & condition == 0.5]))
summaryh(lm(importance ~ n_dwell, d5[topic == "climate" & condition == 0.5]))
summaryh(lm(importance ~ engage, d5[topic == "climate" & condition == 0.5]))
summaryh(lm(importance ~ b1, d5[topic == "climate" & condition == 0.5]))
summaryh(lm(importance ~ like + read + share + ldwell + n_dwell, d5[topic == "climate" & condition == 0.5]))
summaryh(lm(importance ~ like + read + ldwell, d5[topic == "climate" & condition == 0.5]))
summaryh(lm(importance ~ like + read + ldwell + climate_perc, d5[topic == "climate" & condition == 0.5]))

summaryh(lm(rating_combined ~ like, d5[topic == "climate" & condition == 0.5]))
summaryh(lm(rating_combined ~ read, d5[topic == "climate" & condition == 0.5]))
summaryh(lm(rating_combined ~ share, d5[topic == "climate" & condition == 0.5]))
summaryh(lm(rating_combined ~ ldwell, d5[topic == "climate" & condition == 0.5]))
summaryh(lm(rating_combined ~ ldwell_engage0, d5[topic == "climate" & condition == 0.5]))
summaryh(lm(rating_combined ~ n_dwell, d5[topic == "climate" & condition == 0.5]))
summaryh(lm(rating_combined ~ engage, d5[topic == "climate" & condition == 0.5]))
summaryh(lm(rating_combined ~ b1, d5[topic == "climate" & condition == 0.5]))
summaryh(lm(rating_combined ~ like + read + share + ldwell + n_dwell, d5[topic == "climate" & condition == 0.5]))
summaryh(lm(rating_combined ~ like + read + ldwell + climate_perc, d5[topic == "climate" & condition == 0.5]))

summaryh(lm(climate_perc ~ like, d5[topic == "climate" & condition == 0.5]))
summaryh(lm(climate_perc ~ read, d5[topic == "climate" & condition == 0.5]))
summaryh(lm(climate_perc ~ share, d5[topic == "climate" & condition == 0.5]))
summaryh(lm(climate_perc ~ ldwell, d5[topic == "climate" & condition == 0.5]))
summaryh(lm(climate_perc ~ ldwell_engage0, d5[topic == "climate" & condition == 0.5]))
summaryh(lm(climate_perc ~ n_dwell, d5[topic == "climate" & condition == 0.5]))
summaryh(lm(climate_perc ~ engage, d5[topic == "climate" & condition == 0.5]))
summaryh(lm(climate_perc ~ b1, d5[topic == "climate" & condition == 0.5]))
summaryh(lm(climate_perc ~ like + read + share + ldwell + n_dwell, d5[topic == "climate" & condition == 0.5]))
summaryh(lm(climate_perc ~ like + read + ldwell, d5[topic == "climate" & condition == 0.5]))

v <- "importance"
p1 <- plot(correlation::cor_test(d5[condition == 0.5 & topic == "climate"], "share", v, method = 'pearson')) +
    scale_y_continuous(limits = c(1, 6), breaks = 1:6)
p2 <- plot(correlation::cor_test(d5[condition == 0.5 & topic == "climate"], "like", v, method = 'pearson')) +
    scale_y_continuous(limits = c(1, 6), breaks = 1:6)
p3 <- plot(correlation::cor_test(d5[condition == 0.5 & topic == "climate"], "read", v, method = 'pearson')) +
    scale_y_continuous(limits = c(1, 6), breaks = 1:6)
p1 + p2 + p3

v <- "newsworthiness"
p1 <- plot(correlation::cor_test(d5[condition == 0.5 & topic == "climate"], "share", v, method = 'pearson')) +
    scale_y_continuous(limits = c(1, 6), breaks = 1:6)
p2 <- plot(correlation::cor_test(d5[condition == 0.5 & topic == "climate"], "like", v, method = 'pearson')) +
    scale_y_continuous(limits = c(1, 6), breaks = 1:6)
p3 <- plot(correlation::cor_test(d5[condition == 0.5 & topic == "climate"], "read", v, method = 'pearson')) +
    scale_y_continuous(limits = c(1, 6), breaks = 1:6)
p1 + p2 + p3

v <- "rating_combined"
p1 <- plot(correlation::cor_test(d5[condition == 0.5 & topic == "climate"], "share", v, method = 'pearson')) +
    scale_y_continuous(limits = c(1, 6), breaks = 1:6)
p2 <- plot(correlation::cor_test(d5[condition == 0.5 & topic == "climate"], "like", v, method = 'pearson')) +
    scale_y_continuous(limits = c(1, 6), breaks = 1:6)
p3 <- plot(correlation::cor_test(d5[condition == 0.5 & topic == "climate"], "read", v, method = 'pearson')) +
    scale_y_continuous(limits = c(1, 6), breaks = 1:6)
p1 + p2 + p3

v <- "concern"
p1 <- plot(correlation::cor_test(d5[condition == 0.5 & topic == "climate"], "share", v, method = 'pearson')) +
    scale_y_continuous(limits = c(1, 6), breaks = 1:6)
p2 <- plot(correlation::cor_test(d5[condition == 0.5 & topic == "climate"], "like", v, method = 'pearson')) +
    scale_y_continuous(limits = c(1, 6), breaks = 1:6)
p3 <- plot(correlation::cor_test(d5[condition == 0.5 & topic == "climate"], "read", v, method = 'pearson')) +
    scale_y_continuous(limits = c(1, 6), breaks = 1:6)
p1 + p2 + p3

v <- "human_activity"
p1 <- plot(correlation::cor_test(d5[condition == 0.5 & topic == "climate"], "share", v, method = 'pearson')) +
    scale_y_continuous(limits = c(1, 6), breaks = 1:6)
p2 <- plot(correlation::cor_test(d5[condition == 0.5 & topic == "climate"], "like", v, method = 'pearson')) +
    scale_y_continuous(limits = c(1, 6), breaks = 1:6)
p3 <- plot(correlation::cor_test(d5[condition == 0.5 & topic == "climate"], "read", v, method = 'pearson')) +
    scale_y_continuous(limits = c(1, 6), breaks = 1:6)
p1 + p2 + p3

v <- "problem"
p1 <- plot(correlation::cor_test(d5[condition == 0.5 & topic == "climate"], "share", v, method = 'pearson')) +
    scale_y_continuous(limits = c(1, 6), breaks = 1:6)
p2 <- plot(correlation::cor_test(d5[condition == 0.5 & topic == "climate"], "like", v, method = 'pearson')) +
    scale_y_continuous(limits = c(1, 6), breaks = 1:6)
p3 <- plot(correlation::cor_test(d5[condition == 0.5 & topic == "climate"], "read", v, method = 'pearson')) +
    scale_y_continuous(limits = c(1, 6), breaks = 1:6)
p1 + p2 + p3

v <- "hope"
p1 <- plot(correlation::cor_test(d5[condition == 0.5 & topic == "climate"], "share", v, method = 'pearson')) +
    scale_y_continuous(limits = c(1, 6), breaks = 1:6)
p2 <- plot(correlation::cor_test(d5[condition == 0.5 & topic == "climate"], "like", v, method = 'pearson')) +
    scale_y_continuous(limits = c(1, 6), breaks = 1:6)
p3 <- plot(correlation::cor_test(d5[condition == 0.5 & topic == "climate"], "read", v, method = 'pearson')) +
    scale_y_continuous(limits = c(1, 6), breaks = 1:6)
p1 + p2 + p3


v <- "exposure_frequency"
p1 <- plot(correlation::cor_test(d5[condition == 0.5 & topic == "climate"], "share", v, method = 'pearson')) +
    scale_y_continuous(limits = c(1, 6), breaks = 1:6)
p2 <- plot(correlation::cor_test(d5[condition == 0.5 & topic == "climate"], "like", v, method = 'pearson')) +
    scale_y_continuous(limits = c(1, 6), breaks = 1:6)
p3 <- plot(correlation::cor_test(d5[condition == 0.5 & topic == "climate"], "read", v, method = 'pearson')) +
    scale_y_continuous(limits = c(1, 6), breaks = 1:6)
p1 + p2 + p3

v <- "desired_frequency"
p1 <- plot(correlation::cor_test(d5[condition == 0.5 & topic == "climate"], "share", v, method = 'pearson')) +
    scale_y_continuous(limits = c(1, 3), breaks = 1:3)
p2 <- plot(correlation::cor_test(d5[condition == 0.5 & topic == "climate"], "like", v, method = 'pearson')) +
    scale_y_continuous(limits = c(1, 3), breaks = 1:3)
p3 <- plot(correlation::cor_test(d5[condition == 0.5 & topic == "climate"], "read", v, method = 'pearson')) +
    scale_y_continuous(limits = c(1, 3), breaks = 1:3)
p1 + p2 + p3


v <- "n_dwell"
p1 <- plot(correlation::cor_test(d5[condition == 0.5 & topic == "climate"], "share", v, method = 'pearson'))
p2 <- plot(correlation::cor_test(d5[condition == 0.5 & topic == "climate"], "like", v, method = 'pearson'))
p3 <- plot(correlation::cor_test(d5[condition == 0.5 & topic == "climate"], "read", v, method = 'pearson'))
p1 + p2 + p3

v <- "ldwell"
p1 <- plot(correlation::cor_test(d5[condition == 0.5 & topic == "climate"], "share", v, method = 'pearson'))
p2 <- plot(correlation::cor_test(d5[condition == 0.5 & topic == "climate"], "like", v, method = 'pearson'))
p3 <- plot(correlation::cor_test(d5[condition == 0.5 & topic == "climate"], "read", v, method = 'pearson'))
p1 + p2 + p3

v <- "ldwell_engage0"
p1 <- plot(correlation::cor_test(d5[condition == 0.5 & topic == "climate"], "share", v, method = 'pearson'))
p2 <- plot(correlation::cor_test(d5[condition == 0.5 & topic == "climate"], "like", v, method = 'pearson'))
p3 <- plot(correlation::cor_test(d5[condition == 0.5 & topic == "climate"], "read", v, method = 'pearson'))
p1 + p2 + p3

v <- "b1"
p1 <- plot(correlation::cor_test(d5[condition == 0.5 & topic == "climate"], "share", v, method = 'pearson'))
p2 <- plot(correlation::cor_test(d5[condition == 0.5 & topic == "climate"], "like", v, method = 'pearson'))
p3 <- plot(correlation::cor_test(d5[condition == 0.5 & topic == "climate"], "read", v, method = 'pearson'))
p1 + p2 + p3



library(fixest)
feols(ldwell ~ btn_likes | user_id, d0_feed_cc[engaged == 0])
feols(ldwell ~ btn_shares | user_id, d0_feed_cc[engaged == 0])

feols(ldwell ~ btn_likes | user_id, d0_feed[engaged == 0])
feols(ldwell ~ btn_shares | user_id, d0_feed[engaged == 0])



```

