---
title: "heterogeneous treatment effects (hte) with grf"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r}
rm(list = ls())
library(data.table); library(tidyverse); library(grf); library(modelsummary); library(correlation)
theme_set(theme_minimal())
```

```{r}
d00 <- fread("../data/clean/data.csv")
dcov <- fread("../data/clean/data-wide.csv")
first_headline <- fread("../data/clean/first_headline_engagement.csv")
```

```{r prepare covariates}
dcov <- left_join(dcov, first_headline)
setDT(dcov)
dcov
```


```{r prepare data for modeling}
d00[, unique(field)]

# outcome variable to model
yvar <- "climate_importance"
d0 <- d00[field == yvar, .(user_id, y = as.numeric(news_eval), condition = condition + 0.5)]  # code 0/1 (control/treatment)
d0[, .N, condition]

# which covariates/features to use
x <- select(dcov, user_id, age, aot, crt, politicalposition, politicalpref, ses_educationlevel:socialissuespref, -ses_income, engage_firstheadline)

# join
d1 <- left_join(d0, x) |> as.data.table()
d1

datasummary_skim(d1)  # check missing values
nrow(d1)
na.omit(d1) |> nrow()
d1 <- na.omit(d1)  # ensure no missing values

cor_test(d1, "y", "engage_firstheadline", method = "kendall")
```

```{r}
y <- d1$y
X <- select(d1, -user_id, -y, -condition)
# names(df_X)
# X <- as.matrix(X)
w <- d1$condition
w  
```

```{r}
cf <- causal_forest(X, y, w, num.trees = 4000, mtry = ncol(X), min.node.size = 5)
cf

average_treatment_effect(cf, target.sample = "all")  # overall effect of treatment on outcome
average_treatment_effect(cf, target.sample = "treated")

# are there heterogeneous effects?
test_calibration(cf)
```

```{r variable importance}
names(X)
imp <- data.table(x = names(X), imp = variable_importance(cf)[, 1])[order(-imp)]
imp  # most to least important variable
```

```{r}
plot(get_tree(cf, 3))  # plot one example tree
```

```{r}
df_x_mean <- X[, lapply(.SD, mean)]
df_x_mean

n <- 50
vv <- "socialmedia_followers"  # change variable here
pred_vals <- seq(0, 500, length.out = n)  # specify min/max value of the variable above
df_x_mean <- df_x_mean[rep(1, n)]
df_x_mean[, get(vv)]
df_x_mean[, (vv) := pred_vals]
df_x_mean[, ..vv]

cf_predict <- predict(object = cf, newdata = df_x_mean, estimate.variance = TRUE)
setDT(cf_predict)
cf_predict$v <- df_x_mean[, get(vv)]
cf_predict[, se := sqrt(variance.estimates)]
cf_predict

ggplot(cf_predict, aes(v, predictions)) +
    geom_ribbon(aes(ymin = predictions - 1.96 * se, ymax = predictions + 1.96 * se), alpha = 1.0) +
    geom_point(col = "white") +
    labs(x = vv, y = paste0(yvar, "\naverage treatment effect\ntreatment minus control"))
```


```{r}
# vary TWO dimensions at once
df_x_mean <- X[, lapply(.SD, mean)]
df_x_mean

n1 <- 50
v1 <- "socialmedia_followers"  # change variable here
pred_vals <- seq(0, 600, length.out = n1)  # specify min/max value of the variable above
df_x_mean <- df_x_mean[rep(1, n1)]
df_x_mean[, (v1) := pred_vals]

n2 <- 70
df_x_mean <- df_x_mean[rep(seq_len(nrow(df_x_mean)), each = n2), ]
v2 <- "socialmedia_following"  # change variable here
pred_vals <- seq(0, 800, length.out = n2)  # specify min/max value of the variable above
pred_vals <- rep(pred_vals, n1)
df_x_mean[, (v2) := pred_vals]


cf_predict <- predict(object = cf, newdata = df_x_mean, estimate.variance = TRUE)
setDT(cf_predict)
cf_predict$v1 <- df_x_mean[, get(v1)]
cf_predict$v2 <- df_x_mean[, get(v2)]
cf_predict[, se := sqrt(variance.estimates)]
cf_predict

# heatmap
# ggplot()
ggplot(cf_predict, aes(v1, v2, fill= predictions)) + 
  geom_tile() +
    labs(x = v1, y = v2)
```


