---
title: "prep_data"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r}
# https://rdatatable.gitlab.io/data.table/articles/datatable-intro.html
# https://richarddmorey.github.io/BayesFactor/
rm(list = ls())
library(data.table); library(tidyverse); library(rIP)
source("utils_feed.R")
source("creds.R")
```


```{r}
d0 <- fread("../data/raw/eRGOfe_user_form.csv")
```


```{r}
d0 <- d0[!grepl("test", user_id)]
d0[, n_distinct(user_id)]
d0[, unique(field)]
d0[, unique(user_id)]
d0[, n_distinct(user_id)]
```


```{r}
# get users who properly completed study
d0[field == "comments", .N, by = .(user_id)]
d0[field == "gender", .N, by = .(user_id)]
d0[field == "election-newsworthiness", .N, by = .(user_id)]
d0[field == "comments", .N, by = .(user_id)][N != 1]

users_complete <- d0[field == "comments", .N, by = .(user_id)][N == 1, user_id]
users_complete

d0 <- d0[user_id %in% users_complete]
d0
d0[, n_distinct(user_id)]


```


```{r}
# select DVs
cols <- c("attentioncheck1", "attentioncheck2", "election-importance", "election-newsworthiness", "johnny-importance", "johnny-newsworthiness", "climate-importance", "climate-newsworthiness", "election-exposure-frequency", "johnny-exposure-frequency", "climate-exposure-frequency", "election-desired-frequency", "johnny-desired-frequency", "climate-desired-frequency", "climate-concern", "climate-hope", "climate-human-activity", "climate-problem", "climate-cards-perc")
d1 <- d0[field %in% cols, .(user_id, field, response)]
d1[, unique(field)]
d1[, n_distinct(user_id)]
d1[, unique(response)] |> sort()
```


```{r attention check}
ac <- d1[field %in% c("attentioncheck1", "attentioncheck2")]
ac[, .N, .(field, response)]
ac[field == "attentioncheck1", acc := ifelse(response == "3_neither-agree-nor-disagree", 1, 0)]
ac[field == "attentioncheck2", acc := ifelse(response == "very-interested;extremely-interested", 1, 0)]

attention <- ac[, .(attention = mean(acc, na.rm = T)), by = user_id]
attention
attention[, table(attention)]

d1 <- left_join(d1, attention)
setDT(d1)
```


```{r}
d1 <- d1[!field %in% c("attentioncheck1", "attentioncheck2")]
d1[, unique(field)]
glimpse(d1)

d1[, unique(response)]
d1[field != "climate-cards-perc", news_eval := substr(response, 1, 1)]
d1[field == "climate-cards-perc", news_eval := response]
d1[, news_eval := as.numeric(news_eval)]
glimpse(d1)

d1[, mean(news_eval), field]
```


```{r}
# check feed enegagement data
d2 <- get_data("../data/raw/eRGOfe_engagement.csv", n_entities = 100)
d2 <- d2[!grepl("test", user_id)][condition != "null"]
d2 <- make_dwell_data(d2)

d2[, n_distinct(user_id)]
d2[, unique(user_id)]
d2[, n_distinct(entity_id)]
d2[, unique(entity_id)]
d2[, unique(entity_set)]
d2[, unique(veracity)]

d2[user_id %in% users_complete][, n_distinct(user_id)]
d2 <- d2[user_id %in% users_complete]
d2[, n_distinct(user_id)]
glimpse(d2)

# get condition assignment
d3 <- distinct(d2[, .(user_id, condition, ip_address)])
d3[, condition := as.numeric(condition)]
d3[, table(condition)]

d4 <- left_join(d1, d3)
setDT(d4)
```


```{r ip quality}
ips <- copy(d3)
checked <- fread("../data/clean/ips_checked.csv")
ips <- ips[!ip_address %in% checked$ip_address]
ips
if (nrow(ips) > 0) {
    ips_checked <- getIPinfo(ips, "ip_address", iphub_key = iphub_key)
    ips_checked
    ips_checked2 <- left_join(ips, ips_checked, by = c("ip_address" = "IPAddress"))
    ips_checked2 <- ips_checked2[!is.na(IP_Hub_recommend_block)]
    ips_checked2 <- bind_rows(checked, ips_checked2)
    fwrite(ips_checked2, "../data/clean/ips_checked.csv")
} else {
    ips_checked2 <- checked
}
```


```{r exclude based on ip address}
ipscheck <- ips_checked2[, .(user_id, ip_address, ipblock = IP_Hub_recommend_block)]
ipscheck

# check duplicates
ipscheck[, duplicated(ip_address)]
dup_id <- ipscheck[duplicated(ip_address), ip_address]
ipscheck[ip_address %in% dup_id, ipblock := 1]
ipscheck[, table(ipblock)]
```


```{r}
users_wrongrows <- d4[, .N, user_id][N != 17, user_id]
users_wrongrows

dt_main <- d4[!user_id %in% users_wrongrows]
dt_feed <- d2[!user_id %in% users_wrongrows]
```


```{r}
attention
ipscheck[, ip_address := NULL]

dt_main2 <- left_join(dt_main, ipscheck)
dt_feed2 <- left_join(dt_feed, attention) |> left_join(ipscheck)

dt_main2[, unique(condition)]
dt_main2[, condition := condition - 1.5]  # recode condition for model fitting
dt_main2[, unique(condition)]

dt_feed2[, unique(condition)]
dt_feed2[, condition := condition - 1.5]  # recode condition for model fitting
dt_feed2[, unique(condition)]
```


```{r}
dt_main2[, field := gsub('-', '_', field)]
```


```{r}
fwrite(dt_main2, "../data/clean/data.csv")
fwrite(dt_feed2, "../data/clean/data_feed.csv")
```



```{r demographics}
# save politics/ideology/AOT in wide form
cols2 <- c("aot_change-beliefs", "aot_evidence-conflicts", "aot_loyal-beliefs", "aot_maintain-beliefs", "aot_regardless-topic", "aot_true-important", "economicissuespref", "politicalposition", "politicalpref", "socialissuespref", "social-media_accuracy-importance", "social-media_followers", "social-media_following", "social-media_share-politics", "social-media_use-freq", "crt_10-50-printer", "crt_emily-april-may", "crt_mark-adam-28", "crt_mold-bread-40", "crt_pass-second-place", "crt_sheep-15-8-died", "ses_education-level", "ses_education-years", "ses_income", "ses_ladder","age", "covidvaccine", "ethnicity", "gender", "comments", "random", "study-duration")
d5 <- d0[field %in% cols2, .(user_id, field, response)]

d5 <- d5[, .SD[1], .(user_id, field)] 

# take first response/row per user per question
d5[, .N, user_id][, table(N)]  # any weird people? 

d5[, unique(field)]
d5[, n_distinct(user_id)]
d5[, unique(response)] |> sort()
d5[field != "comments", unique(response)]
# if contains _, then it's coded as value_label
d5[, value := ifelse(grepl("_", response, fixed = TRUE), substr(response, 1, 1), response)]
d5
d5[is.na(value)]

d6 <- dcast(d5, user_id ~ field, value.var = c("value"))

# numeric columns
num_cols2 <- c("aot_change-beliefs", "aot_evidence-conflicts", "aot_loyal-beliefs", "aot_maintain-beliefs", "aot_regardless-topic", "aot_true-important", "economicissuespref", "politicalposition", "politicalpref", "socialissuespref", "social-media_accuracy-importance", "social-media_followers", "social-media_following", "social-media_share-politics", "social-media_use-freq", "crt_10-50-printer", "crt_mark-adam-28", "crt_mold-bread-40", "crt_pass-second-place", "crt_sheep-15-8-died", "ses_education-level", "ses_education-years", "ses_income", "ses_ladder","age", "covidvaccine", "study-duration")

d6[, num_cols2] <- lapply(num_cols2, function(x) as.numeric(d6[[x]]))
setnames(d6, gsub("-", "", names(d6)))
glimpse(d6)

# mean aot (reverse-coded)
aot_r <- 7 - select(d6, starts_with("aot_")) |> rowMeans()
d6[, aot := aot_r]
d6
```


```{r crt accuracy}
select(d6, starts_with("crt_"))

d6[, table(crt_1050printer)]
d6[, crt_1050printer := ifelse(crt_1050printer == 10, 1, 0)]

d6[, table(crt_emilyaprilmay)]
d6[, crt_emilyaprilmay := str_trim(tolower(crt_emilyaprilmay), side = "both")]
d6[grepl("emi", crt_emilyaprilmay), table(crt_emilyaprilmay)]
d6[!grepl("emi", crt_emilyaprilmay), table(crt_emilyaprilmay)]
d6[, crt_emily := ifelse(grepl("emi", crt_emilyaprilmay), 1, 0)]
d6[, .(crt_emilyaprilmay, crt_emily)][order(crt_emily)] |> distinct()

d6[, table(crt_markadam28)]
d6[, crt_markadam28 := ifelse(crt_markadam28 == 4, 1, 0)]

d6[, table(crt_moldbread40)]
d6[, crt_moldbread40 := ifelse(crt_moldbread40 == 39, 1, 0)]

d6[, table(crt_passsecondplace)]
d6[, crt_passsecondplace := ifelse(crt_passsecondplace == 2, 1, 0)]

d6[, table(crt_sheep158died)]
d6[, crt_sheep158died := ifelse(crt_sheep158died == 8, 1, 0)]

crt <- select(d6, starts_with("crt_"), -crt_emilyaprilmay) |> rowMeans()
d6[, crt := crt]
```


```{r}
fwrite(d6, "../data/clean/data-wide.csv")
d5_code <- d5[, .(n = .N), .(field, response, value)][order(field, response)]
fwrite(d5_code, "../data/clean/data-wide-code.csv")
```

