---
title: "analyze"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r}
rm(list = ls())
library(data.table); library(tidyverse); library(correlation)
library(BayesFactor); library(BFpack); library(ggbeeswarm); library(patchwork)
theme_set(theme_minimal())
```

```{r}
d0_feed <- fread("../data/clean/data_feed.csv")


glimpse(d0_feed)

d0_feed_like_flipflopers <- d0_feed[likes_0+likes_1 >= 2]
d0_feed_read_later_flipflopers <- d0_feed[read_later_0+read_later_1 >= 2]
d0_feed_share_flipflopers <- d0_feed[shares_0+shares_1 >= 2]

table(d0_feed_like_flipflopers$condition, d0_feed_like_flipflopers$entity_set)
table(d0_feed_read_later_flipflopers$condition, d0_feed_read_later_flipflopers$entity_set)
table(d0_feed_share_flipflopers$condition, d0_feed_share_flipflopers$entity_set)

# overall, more flip flops of all 3 kinds happened in the -0.5 aka control condition


```


```{r}
d0_feed[, likes := likes_0 + likes_1]
d0_feed[, shares := shares_0 + shares_1]
d0_feed[, read_later := read_later_0 + read_later_1]

d0_feed[, likesf := ifelse(likes >= 2, likes - 1, 0)]
d0_feed[, sharesf := ifelse(shares >= 2, shares - 1, 0)]
d0_feed[, read_laterf := ifelse(read_later >= 2, read_later - 1, 0)]

d0_feed[, .N, user_id]
d0_feed_avg <- d0_feed[, .(likesf = mean(likesf), likes = mean(likes), 
                           sharesf = mean(sharesf), shares = mean(shares), 
                           read_laterf = mean(read_laterf), read_later = mean(read_later) 
                           ), .(user_id, condition)]
d0_feed_avg_long <- melt(d0_feed_avg, id.vars = c("user_id", "condition"))
d0_feed_avg_long

d0_feed_avg[, ]

d0_feed_sum <- d0_feed[, .(likesf = sum(likesf), likes = sum(likes), 
                           sharesf = sum(sharesf), shares = sum(shares), 
                           read_laterf = sum(read_laterf), read_later = sum(read_later) 
                           ), .(user_id, condition)]

d0_feed_avg_w_ratings <- left_join(d0_feed_avg, d3)

d0_feed_sum_w_ratings <- left_join(d0_feed_sum, d3)

correlation::cor_test(d0_feed_sum_w_ratings, "likesf", "importance", method = 'spearman') |> plot()

correlation::cor_test(d0_feed_sum_w_ratings, "likesf", "newsworthiness", method = 'spearman') |> plot()

correlation::cor_test(d0_feed_sum_w_ratings, "sharesf", "newsworthiness", method = 'spearman') |> plot()

correlation::cor_test(d0_feed_sum_w_ratings, "read_laterf", "newsworthiness", method = 'spearman') |> plot()
```


```{r}
d4 <- distinct(d0_feed_sum[, .(user_id, condition, likesf)])
d4[, condition := condition + 0.5]
summary(lm(likesf ~ condition, d4))

p1 <- ggplot(d4, aes(factor(condition, labels = c("control", "treatment")), likesf)) +
    geom_quasirandom(alpha = 0.3, size = 0.8) +
    stat_summary(fun = mean, geom = 'point', shape = 95, size = 6) +
    stat_summary(fun.data = mean_cl_normal, geom = 'errorbar', width = 0, size = 1.1) +
    scale_y_continuous(limits = c(0, 10)) +
    labs(x = "", y = "self-reported percent will smith cards seen")
p1

# ggsave("../figures/manipulation_check.png", p1, dpi = 300, width = 5, height = 5, bg = "white")
```



```{r}
d1 <- fread("../data/clean/data.csv")
d1[, n_distinct(user_id), keyby = .(condition)]
d1[, n_distinct(user_id), keyby = .(condition, attention, ipblock)]  # users per condition

d2 <- d1[attention == 1.0 & ipblock == 0]
d2[, n_distinct(user_id), keyby = .(condition, attention, ipblock)]

# remove alphanumeric response column, ip address and country codes
d2 <- select(d2, user_id, condition, field, news_eval)
perc <- d2[field == "willsmith_cards_perc", .(user_id, news_eval)]
setnames(perc, c("user_id", "willsmith_perc"))
perc

d2 <- d2[field != "willsmith_cards_perc"] |> left_join(perc) 
setDT(d2)
```

```{r}
d2 <- separate(d2, field, c("topic", "question"), "_")
d3 <- dcast(d2, user_id + condition + topic + willsmith_perc ~ question, value.var = "news_eval")
d3[, rating_combined := (importance + newsworthiness) / 2]
d3
```

```{r}
unique_users <- unique(d0_feed_like_flipflopers$user_id)

d5 <- d2[user_id %in% unique_users]
d5

dodge <- 0.8
p2 <- ggplot(d5, aes(question, news_eval, col = factor(condition, labels = c("control", "treatment")))) +
    facet_wrap(~ topic) +
    geom_quasirandom(alpha = 0.3, dodge = dodge, size = 0.8) +
    stat_summary(fun = mean, geom = 'point', shape = 95, size = 6, position = position_dodge(dodge)) +
    stat_summary(fun.data = mean_cl_normal, geom = 'errorbar', width = 0, size = 1.1, position = position_dodge(dodge)) +
    scale_y_continuous(limits = c(0, 7), breaks = 1:6) +
    labs(x = "", y = "rating", col = "condition")
p2

ggsave("../figures/main_effect_folks_who_flipflopped_likes_any_card.png", p2, dpi = 300, width = 13, height = 5, bg = "white")

d0_feed_like_flipflopers_ws <- d0_feed_like_flipflopers[entity_set == "22apr25_willsmith"]
unique_users <- unique(d0_feed_like_flipflopers_ws$user_id)

d5 <- d2[user_id %in% unique_users]
d5

dodge <- 0.8
p2 <- ggplot(d5, aes(question, news_eval, col = factor(condition, labels = c("control", "treatment")))) +
    facet_wrap(~ topic) +
    geom_quasirandom(alpha = 0.3, dodge = dodge, size = 0.8) +
    stat_summary(fun = mean, geom = 'point', shape = 95, size = 6, position = position_dodge(dodge)) +
    stat_summary(fun.data = mean_cl_normal, geom = 'errorbar', width = 0, size = 1.1, position = position_dodge(dodge)) +
    scale_y_continuous(limits = c(0, 7), breaks = 1:6) +
    labs(x = "", y = "rating", col = "condition")
p2

ggsave("../figures/main_effect_folks_who_flipflopped_likes_WS_card.png", p2, dpi = 300, width = 13, height = 5, bg = "white")

```


```{r}
d0_feed_read_later_flipflopers_ws <- d0_feed_read_later_flipflopers[entity_set == "22apr25_willsmith"]

unique_users <- unique(d0_feed_read_later_flipflopers$user_id)

d5 <- d2[user_id %in% unique_users]
d5

dodge <- 0.8
p2 <- ggplot(d5, aes(question, news_eval, col = factor(condition, labels = c("control", "treatment")))) +
    facet_wrap(~ topic) +
    geom_quasirandom(alpha = 0.3, dodge = dodge, size = 0.8) +
    stat_summary(fun = mean, geom = 'point', shape = 95, size = 6, position = position_dodge(dodge)) +
    stat_summary(fun.data = mean_cl_normal, geom = 'errorbar', width = 0, size = 1.1, position = position_dodge(dodge)) +
    scale_y_continuous(limits = c(0, 7), breaks = 1:6) +
    labs(x = "", y = "rating", col = "condition")
p2

ggsave("../figures/main_effect_folks_who_flipflopped_readlater_any_card.png", p2, dpi = 300, width = 13, height = 5, bg = "white")

unique_users <- unique(d0_feed_read_later_flipflopers_ws$user_id)

d5 <- d2[user_id %in% unique_users]
d5

dodge <- 0.8
p2 <- ggplot(d5, aes(question, news_eval, col = factor(condition, labels = c("control", "treatment")))) +
    facet_wrap(~ topic) +
    geom_quasirandom(alpha = 0.3, dodge = dodge, size = 0.8) +
    stat_summary(fun = mean, geom = 'point', shape = 95, size = 6, position = position_dodge(dodge)) +
    stat_summary(fun.data = mean_cl_normal, geom = 'errorbar', width = 0, size = 1.1, position = position_dodge(dodge)) +
    scale_y_continuous(limits = c(0, 7), breaks = 1:6) +
    labs(x = "", y = "rating", col = "condition")
p2

ggsave("../figures/main_effect_folks_who_flipflopped_readlater_WS_card.png", p2, dpi = 300, width = 13, height = 5, bg = "white")

```



```{r}
d0_feed_share_flipflopers_ws <- d0_feed_share_flipflopers[entity_set == "22apr25_willsmith"]

unique_users <- unique(d0_feed_share_flipflopers$user_id)

d5 <- d2[user_id %in% unique_users]
d5

dodge <- 0.8
p2 <- ggplot(d5, aes(question, news_eval, col = factor(condition, labels = c("control", "treatment")))) +
    facet_wrap(~ topic) +
    geom_quasirandom(alpha = 0.3, dodge = dodge, size = 0.8) +
    stat_summary(fun = mean, geom = 'point', shape = 95, size = 6, position = position_dodge(dodge)) +
    stat_summary(fun.data = mean_cl_normal, geom = 'errorbar', width = 0, size = 1.1, position = position_dodge(dodge)) +
    scale_y_continuous(limits = c(0, 7), breaks = 1:6) +
    labs(x = "", y = "rating", col = "condition")
p2

ggsave("../figures/main_effect_folks_who_flipflopped_shares_any_card.png", p2, dpi = 300, width = 13, height = 5, bg = "white")

unique_users <- unique(d0_feed_share_flipflopers_ws$user_id)

d5 <- d2[user_id %in% unique_users]
d5

dodge <- 0.8
p2 <- ggplot(d5, aes(question, news_eval, col = factor(condition, labels = c("control", "treatment")))) +
    facet_wrap(~ topic) +
    geom_quasirandom(alpha = 0.3, dodge = dodge, size = 0.8) +
    stat_summary(fun = mean, geom = 'point', shape = 95, size = 6, position = position_dodge(dodge)) +
    stat_summary(fun.data = mean_cl_normal, geom = 'errorbar', width = 0, size = 1.1, position = position_dodge(dodge)) +
    scale_y_continuous(limits = c(0, 7), breaks = 1:6) +
    labs(x = "", y = "rating", col = "condition")
p2

ggsave("../figures/main_effect_folks_who_flipflopped_shares_WS_card.png", p2, dpi = 300, width = 13, height = 5, bg = "white")

```

