---
title: "scratch"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r}
rm(list = ls())
source("utils_feed.R")

dat <- get_data("../data/raw/ej3MkW_engagement.csv", n_entities = 100)
dt_dwell <- make_dwell_data(dat)
dt_dwell

library(fixest)
feglm(likes_1 ~ btn_likes | user_id, dt_dwell, family = "quasipoisson")
feglm(shares_1 ~ btn_shares | user_id, dt_dwell, family = "quasipoisson")
```

```{r}
d0[, unique(field)]
d1 <- d0[field == "politicalpref",]
d1[, unique(response)]
d1[, resp := substr(response, 1, 1)]
d1[, resp := as.numeric(resp)]
hist(d1$resp, main = "demrep")



d1 <- d0[field == "economicissuespref",]
d1[, unique(response)]
d1[, resp := substr(response, 1, 1)]
d1[, resp := as.numeric(resp)]
hist(d1$resp, main = "economicissuespref")

```

```{r}
mod
head(coef(mod)$user_id)

head(coef(mod)$user_id[, , 1])
head(coef(mod)$user_id[, , 2])

fe <- fixef(mod, summary = FALSE)
re <- fixef(mod, summary = FALSE)
fe
head(re)
fixef(mod)

ranef(mod)$user_id[,,1][, "Estimate"]

head(ranef(mod)$user_id[,,1])
head(ranef(mod)$user_id[,,2])


head(coef(mod)$user_id[,,1])
head(ranef(mod)$user_id[,,1])[, 'Estimate'] + fixef(mod)[1, 'Estimate']

head(coef(mod)$user_id[,,2])
head(ranef(mod)$user_id[,,2])[, "Estimate"] + fixef(mod)[2, 'Estimate']


posterior_summary(fe[, 1] + re[, 2])
fe[, 1] + re[, 2]

re$user_id
```

```{r}
data("sleepstudy", package ="lme4")
df <- sleepstudy
df$Days2 <- factor(ifelse(df$Days < 5, 0, 1))
fit <- brm(Reaction ~ Days2 + (Days2 | Subject), df)
fe <- fixef(fit, summary = FALSE)
re <- ranef(fit, summary = FALSE)
head(re)
(res1 <- posterior_summary(fe[, 2] + re$Subject[, , 2]))
(res2 <- coef(fit)$Subject[, , 2])
all.equal(res1, res2)
```

